use_frameworks!

platform :ios, '9.0'

target 'SPComponentDemo_Example' do
  pod 'SPComponentDemo', :path => '../'

  target 'SPComponentDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
